name: 04 basics context

on:
    workflow_dispatch

jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Print Context Data
              run: echo ${{github}}
            #   run: echo ${{github.actor}}