name: 04 basics context

on:
    workflow_dispatch

jobs:
    print-context-data:
        runs-on: ubuntu-latest
        steps:
            - name: Print Context Data
<<<<<<< HEAD
              # run: echo ${{github}}
              run: echo ${{github.actor}}
=======
            #   run: echo ${{github}}
              run: echo ${{github.actor}}
>>>>>>> fd425d1 (d)
